### ISSUE TITLE
Missing python module backend.ttypes

### ISSUE THREAD

**Issue by eritpchy** [kenvix/ComplexBot#10]
Python backend started
stdout
07:16:09
Version 1.0
stdout
07:16:09
Traceback (most recent call last):
stderr
07:16:09
  File "main.py", line 6, in <module>
stderr
07:16:09
    import apiserver
stderr
07:16:09
  File "/backend/apiserver.py", line 11, in <module>
stderr
07:16:09
    from backend.ttypes import TextClassificationResult, RPCException
stderr
07:16:09
ModuleNotFoundError: No module named 'backend.ttypes'

**Comment by eritpchy** [comment]
已经解决了https://github.com/eritpchy/ComplexBot/commit/517c67e820a166a3a0f0af4bac12c4086637c48e, 不过建议还是要上传一下生成的文件
