### ISSUE TITLE
掉线后不会自动重连

### ISSUE THREAD

**Issue by eritpchy** [kenvix/ComplexBot#12]
2020-09-13 20:13:55 I/Bot 123456789: Reconnected successfully in 0.0s
2020-09-13 20:13:55 I/Net 123456789: Syncing friend message history...
2020-09-13 20:13:55 V/Net 123456789: Send: MessageSvc.PbGetMsg
2020-09-13 20:13:55 W/Net 123456789: Network force offline: returnCode = -10008
2020-09-13 20:13:55 I/Bot 123456789: Connection lost, retrying login
2020-09-13 20:13:55 I/Bot 123456789: Reconnected successfully in 0.0s
2020-09-13 20:13:55 I/Net 123456789: Syncing friend message history...
2020-09-13 20:13:55 V/Net 123456789: Send: MessageSvc.PbGetMsg
2020-09-13 20:13:55 W/Net 123456789: Network force offline: returnCode = -10008
2020-09-13 20:13:55 I/Bot 123456789: Connection lost, retrying login
2020-09-13 20:13:56.168 [ERROR][DefaultDispatcher-worker-7: c.k.c.ComplexBotMiraiComponent] Mirai Exception on coroutineContext [com.kenvix.complexbot.ComplexBotMiraiComponent$$special$$inlined$CoroutineExceptionHandler$1@5b347086, CoroutineName(Mirai Bot), SupervisorJobImpl{Active}@1e36f584, Dispatchers.IO]
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.remove(Unknown Source)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invokeSuspend(BotImpl.kt:94)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invoke(BotImpl.kt)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:271)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:242)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1$invokeSuspend$$inlined$use$lambda$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:466)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2020-09-13 20:14:00 V/Net 123456789: Send: MessageSvc.PbGetMsg
2020-09-13 20:14:00 W/Net 123456789: Network force offline: returnCode = -10008
2020-09-13 20:14:00 I/Bot 123456789: Connection lost, retrying login
2020-09-13 20:14:00 V/Net 123456789: Send: MessageSvc.PbGetMsg
2020-09-13 20:14:00.592 [ERROR][DefaultDispatcher-worker-7: c.k.c.ComplexBotMiraiComponent] Mirai Exception on coroutineContext [com.kenvix.complexbot.ComplexBotMiraiComponent$$special$$inlined$CoroutineExceptionHandler$1@5b347086, CoroutineName(Mirai Bot), SupervisorJobImpl{Active}@1e36f584, Dispatchers.IO]
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.remove(Unknown Source)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invokeSuspend(BotImpl.kt:94)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invoke(BotImpl.kt)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:271)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:242)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1$invokeSuspend$$inlined$use$lambda$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:466)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2020-09-13 20:14:00 W/Net 123456789: Network force offline: returnCode = -10008
2020-09-13 20:14:00 I/Bot 123456789: Connection lost, retrying login
2020-09-13 20:14:00.640 [ERROR][DefaultDispatcher-worker-7: c.k.c.ComplexBotMiraiComponent] Mirai Exception on coroutineContext [com.kenvix.complexbot.ComplexBotMiraiComponent$$special$$inlined$CoroutineExceptionHandler$1@5b347086, CoroutineName(Mirai Bot), SupervisorJobImpl{Active}@1e36f584, Dispatchers.IO]
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.remove(Unknown Source)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invokeSuspend(BotImpl.kt:94)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invoke(BotImpl.kt)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:271)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:242)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1$invokeSuspend$$inlined$use$lambda$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:466)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2020-09-13 20:14:00 V/Net 123456789: Send: MessageSvc.PbGetMsg
2020-09-13 20:14:00 W/Net 123456789: Network force offline: returnCode = -10008
2020-09-13 20:14:00 I/Bot 123456789: Connection lost, retrying login
2020-09-13 20:14:00.700 [ERROR][DefaultDispatcher-worker-7: c.k.c.ComplexBotMiraiComponent] Mirai Exception on coroutineContext [com.kenvix.complexbot.ComplexBotMiraiComponent$$special$$inlined$CoroutineExceptionHandler$1@5b347086, CoroutineName(Mirai Bot), SupervisorJobImpl{Active}@1e36f584, Dispatchers.IO]
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.remove(Unknown Source)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invokeSuspend(BotImpl.kt:94)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invoke(BotImpl.kt)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:271)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:242)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1$invokeSuspend$$inlined$use$lambda$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:466)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2020-09-13 20:14:01 I/Bot 123456789: Connection lost, retrying login
2020-09-13 20:14:01.041 [ERROR][DefaultDispatcher-worker-2: c.k.c.ComplexBotMiraiComponent] Mirai Exception on coroutineContext [com.kenvix.complexbot.ComplexBotMiraiComponent$$special$$inlined$CoroutineExceptionHandler$1@5b347086, CoroutineName(Mirai Bot), SupervisorJobImpl{Active}@1e36f584, Dispatchers.IO]
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.remove(Unknown Source)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invokeSuspend(BotImpl.kt:94)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invoke(BotImpl.kt)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:271)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:242)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$startPacketReceiverJobOrKill$2$rawInput$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:88)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2020-09-13 20:14:05 V/Net 123456789: Send: MessageSvc.PbGetMsg
2020-09-13 20:14:05 E/Net 123456789: Exception in NetworkHandler
java.net.SocketException: Broken pipe (Write failed)
        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.base/java.net.SocketOutputStream.socketWrite(Unknown Source)
        at java.base/java.net.SocketOutputStream.write(Unknown Source)
        at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.base/java.io.BufferedOutputStream.flush(Unknown Source)
        at net.mamoe.mirai.qqandroid.utils.PlatformSocket$send$4.invokeSuspend(PlatformSocket.kt:52)
        at net.mamoe.mirai.qqandroid.utils.PlatformSocket$send$4.invoke(PlatformSocket.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.qqandroid.utils.PlatformSocket.send(PlatformSocket.kt:50)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$sendAndExpect$7.invokeSuspend(QQAndroidBotNetworkHandler.kt:654)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$sendAndExpect$7.invoke(QQAndroidBotNetworkHandler.kt)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:679)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$sendAndExpect$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-09-13 20:14:05 E/Net 123456789: Exception in NetworkHandler
java.net.SocketException: Broken pipe (Write failed)
        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.base/java.net.SocketOutputStream.socketWrite(Unknown Source)
        at java.base/java.net.SocketOutputStream.write(Unknown Source)
        at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.base/java.io.BufferedOutputStream.flush(Unknown Source)
        at net.mamoe.mirai.qqandroid.utils.PlatformSocket$send$4.invokeSuspend(PlatformSocket.kt:52)
        at net.mamoe.mirai.qqandroid.utils.PlatformSocket$send$4.invoke(PlatformSocket.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.qqandroid.utils.PlatformSocket.send(PlatformSocket.kt:50)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$sendAndExpect$7.invokeSuspend(QQAndroidBotNetworkHandler.kt:654)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$sendAndExpect$7.invoke(QQAndroidBotNetworkHandler.kt)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:679)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$sendAndExpect$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-09-13 20:14:22 I/Bot 123456789: Connection lost, retrying login
2020-09-13 20:14:22.760 [ERROR][DefaultDispatcher-worker-7: c.k.c.ComplexBotMiraiComponent] Mirai Exception on coroutineContext [com.kenvix.complexbot.ComplexBotMiraiComponent$$special$$inlined$CoroutineExceptionHandler$1@5b347086, CoroutineName(Mirai Bot), SupervisorJobImpl{Active}@1e36f584, Dispatchers.IO]
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.remove(Unknown Source)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invokeSuspend(BotImpl.kt:94)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invoke(BotImpl.kt)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:271)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:242)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$startHeartbeatJobOrKill$1$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:110)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by eritpchy** [comment]
https://github.com/mamoe/mirai/issues/598 看来是mirai的问题
